---
title: "Gráfico de radar"
author: "Freddy F. Tapia C."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Estadísticas de los mejores jugadores FIFA 18

```{r ,echo=FALSE, include=FALSE}
#CARGO LIBRERIA
library(highcharter)
```

```{r ,echo=TRUE}
#DATA 2018
data_18 <- read.csv("CompleteDataset.csv")

#FILTRO DATA
data_18 <- data_18[,c(2,3,14:22,32:47)]

d_18 <- data_18[1:10,c(1,3,4,23,25,26,17,20)]

#ARREGLO DATA
rownames(d_18) <- d_18[,1]
d_18 <- d_18[,-1]
d_18$Acceleration <- as.numeric(as.character(d_18$Acceleration))
d_18$Aggression <- as.numeric(as.character(d_18$Aggression))
d_18$Stamina <- as.numeric(as.character(d_18$Stamina))
d_18$Strength <- as.numeric(as.character(d_18$Strength))
d_18$Vision <- as.numeric(as.character(d_18$Vision))
d_18$Positioning <- as.numeric(as.character(d_18$Positioning))
d_18$Shot.power <- as.numeric(as.character(d_18$Shot.power))

d_18 <- t(d_18)
```

## Data a usar

```{r, echo=TRUE}
DT::datatable(d_18)
```

## Gráfico de un jugador

```{r, echo=TRUE}
#EJEMPLO FIFA
rownames(d_18) <- c("Aceleración","Agresividad","Resistencia",
                    "Fuerza","Visión","Posicionamiento","Potencia de disparo")

hc <- highchart() %>%
  hc_chart(polar = T) %>% 
  hc_xAxis(categories = rownames(d_18), 
           labels = list(style = list(fontSize= '14px')), title =NULL, tickmarkPlacement = "on", lineWidth = 0) %>% 
  hc_plotOptions(series = list(marker = list(enabled = F))) %>% 
  hc_yAxis(gridLineInterpolation = "polygon", lineWidth = 0, min = 0) %>% 
  hc_add_series(name = colnames(d_18)[2], as.numeric(d_18[,2]), type ="area", color = "#4472c4", pointPlacement = "on")

hc
```

## Gráfico de dos o más jugadores

```{r, echo=TRUE}
#EJEMPLO DOS EN UNO
hc2 <- highchart() %>%
  hc_chart(polar = T) %>% 
  hc_xAxis(categories = rownames(d_18), 
           labels = list(style = list(fontSize= '14px')), title =NULL, tickmarkPlacement = "on", lineWidth = 0) %>% 
  hc_plotOptions(series = list(marker = list(enabled = F))) %>% 
  hc_yAxis(gridLineInterpolation = "polygon", lineWidth = 0, min = 0) %>% 
  hc_add_series(name = colnames(d_18)[1], as.numeric(d_18[,1]), type ="area", color = "#4472c4", pointPlacement = "on") %>% 
  hc_add_series(name = colnames(d_18)[6], as.numeric(d_18[,6]), type ="area", color = "green", pointPlacement = "on") %>% 
  hc_add_series(name = colnames(d_18)[2], as.numeric(d_18[,2]), type ="area", color = "blue", pointPlacement = "on")%>% 
  hc_add_series(name = colnames(d_18)[3], as.numeric(d_18[,3]), type ="area", color = "yellow", pointPlacement = "on")

hc2
```

## Comparativo entre arqueros

```{r, echo=TRUE}
#EJEMPLO DOS EN UNO
hc2 <- highchart() %>%
  hc_chart(polar = T) %>% 
  hc_xAxis(categories = rownames(d_18), 
           labels = list(style = list(fontSize= '14px')), title =NULL, tickmarkPlacement = "on", lineWidth = 0) %>% 
  hc_plotOptions(series = list(marker = list(enabled = F))) %>% 
  hc_yAxis(gridLineInterpolation = "polygon", lineWidth = 0, min = 0) %>% 
  hc_add_series(name = colnames(d_18)[5], as.numeric(d_18[,5]), type ="area", color = "#4472c4", pointPlacement = "on") %>% 
  hc_add_series(name = colnames(d_18)[7], as.numeric(d_18[,7]), type ="area", color = "green", pointPlacement = "on")

hc2
```

